// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd026w0e46GPMldToRTcIo6gC9aWij47Q',
    appId: '1:1015069589191:web:a3a80f075a5b451c6348e2',
    messagingSenderId: '1015069589191',
    projectId: 'finance-8f9a0',
    authDomain: 'finance-8f9a0.firebaseapp.com',
    storageBucket: 'finance-8f9a0.appspot.com',
    measurementId: 'G-KCTVT9GC31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTCK5jhW3PxzRyRJG62Mi34LjZxYNqYws',
    appId: '1:1015069589191:android:cd96d28153bf7a456348e2',
    messagingSenderId: '1015069589191',
    projectId: 'finance-8f9a0',
    storageBucket: 'finance-8f9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7SFREibNgYSFJ9S8kiL2sqrPpGZPkLEE',
    appId: '1:1015069589191:ios:b185cc3b08fd20a96348e2',
    messagingSenderId: '1015069589191',
    projectId: 'finance-8f9a0',
    storageBucket: 'finance-8f9a0.appspot.com',
    iosClientId:
        '1015069589191-9n7qjsmv18cien7l2j4l0tn1i7drof4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinancial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7SFREibNgYSFJ9S8kiL2sqrPpGZPkLEE',
    appId: '1:1015069589191:ios:b185cc3b08fd20a96348e2',
    messagingSenderId: '1015069589191',
    projectId: 'finance-8f9a0',
    storageBucket: 'finance-8f9a0.appspot.com',
    iosClientId:
        '1015069589191-9n7qjsmv18cien7l2j4l0tn1i7drof4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinancial',
  );
}
