// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1UsRKiHJi0hZvzF2wOtGL3MlMjeltpSE',
    appId: '1:1015064810898:web:ce9aac313c64af43851d4b',
    messagingSenderId: '1015064810898',
    projectId: 'personalfinance-36baf',
    authDomain: 'personalfinance-36baf.firebaseapp.com',
    storageBucket: 'personalfinance-36baf.appspot.com',
    measurementId: 'G-YVG4XRGTDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-0V2b7APveeSZy5D2ZaN2mYfMvHVJQU',
    appId: '1:1015064810898:android:f3ea17f67673abdb851d4b',
    messagingSenderId: '1015064810898',
    projectId: 'personalfinance-36baf',
    storageBucket: 'personalfinance-36baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2wOKnH3twjxd8lVVe539Ipad-OJ43SE',
    appId: '1:1015064810898:ios:8d61a879b0bb15e4851d4b',
    messagingSenderId: '1015064810898',
    projectId: 'personalfinance-36baf',
    storageBucket: 'personalfinance-36baf.appspot.com',
    iosClientId:
        '1015064810898-sc1q6iput7g9vgk189nms1opechcfpk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinancial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2wOKnH3twjxd8lVVe539Ipad-OJ43SE',
    appId: '1:1015064810898:ios:8d61a879b0bb15e4851d4b',
    messagingSenderId: '1015064810898',
    projectId: 'personalfinance-36baf',
    storageBucket: 'personalfinance-36baf.appspot.com',
    iosClientId:
        '1015064810898-sc1q6iput7g9vgk189nms1opechcfpk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinancial',
  );
}
